# Generated by Django 5.0.7 on 2024-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_fooditem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10),
        ),
    ]
