# Generated by Django 5.0.7 on 2024-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_fooditem_created_at_fooditem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
