# Generated by Django 5.0.7 on 2024-07-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_alter_fooditem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
