# Generated by Django 5.0.7 on 2024-08-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_category_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='veg',
            field=models.BooleanField(default=True),
        ),
    ]
