# Generated by Django 5.1.1 on 2024-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_fooditem_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.JSONField(default=list, blank=True, null=True),
        ),
    ]
