# Generated by Django 5.1.1 on 2024-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
