# Generated by Django 5.1.1 on 2024-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0023_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
