# Generated by Django 5.1.1 on 2024-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0024_alter_category_image_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
