# Generated by Django 5.1.1 on 2024-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0027_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
