# Generated by Django 5.1.1 on 2024-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_tenant_subscription_from_tenant_subscription_to'),
        ('foods', '0030_alter_table_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('tenant', 'table_number')},
        ),
    ]
