# Generated by Django 5.1.1 on 2024-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0031_alter_table_table_number_alter_table_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
