# Generated by Django 5.2 on 2025-04-14 16:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_bill_no', models.IntegerField(blank=True, null=True)),
                ('hot_bill_no', models.IntegerField(blank=True, null=True)),
                ('day_calculation_method', models.CharField(choices=[('hotel_standard', 'Hotel Standard'), ('24h_basis', '24 Hours')], default='hotel_standard', max_length=20)),
                ('bill_no', models.IntegerField(blank=True, null=True)),
                ('gst_bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_type', models.CharField(choices=[('HOT', 'Hotel'), ('RES', 'Restaurant')], max_length=3)),
                ('customer_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.JSONField(blank=True, default=list)),
                ('modified_by', models.JSONField(blank=True, default=list)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
