# Generated by Django 5.1.2 on 2024-11-02 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='bill',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='modified_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gst_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='modified_at',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
