# Generated by Django 5.1.2 on 2024-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_bill_billing_date_remove_bill_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='sub_total',
            new_name='total',
        ),
    ]
