# Generated by Django 5.1.2 on 2024-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_sub_total_bill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_number',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='hot_bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='res_bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='service_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='service_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
