# Generated by Django 5.1.2 on 2024-11-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_bill_bill_number_bill_bill_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='booking',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='order',
            new_name='order_id',
        ),
    ]
