# Generated by Django 5.1.2 on 2024-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_booking_bill_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('HOT', 'Hotel'), ('RES', 'Restaurant')], max_length=3),
        ),
    ]
