# Generated by Django 5.1.2 on 2024-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
