# Generated by Django 5.1.2 on 2024-11-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bill_customer_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='unpaid', max_length=20),
        ),
    ]
