# Generated by Django 5.1.2 on 2024-11-09 19:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_bill_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpayment',
            old_name='amount',
            new_name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='bill',
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
