# Generated by Django 5.1.2 on 2024-11-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_rename_amount_billpayment_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='day_calculation_method',
            field=models.CharField(choices=[('hotel_standard', 'Hotel Standard'), ('24h_basis', '24 Hours')], default='hotel_standard', max_length=20),
        ),
    ]
