# Generated by Django 5.0.7 on 2024-08-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_tenant_total_tables'),
        ('order', '0002_remove_order_table_number_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.table'),
        ),
    ]
