# Generated by Django 5.0.7 on 2024-08-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('take_away', 'Take Away'), ('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('online', 'Online'), ('hotel', 'Hotel')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('due', 'Due'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
