# Generated by Django 5.0.7 on 2024-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_tenant_total_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='total_tables',
            field=models.IntegerField(default=0),
        ),
    ]
