# Generated by Django 5.2 on 2025-04-14 16:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_hotel_feature', models.BooleanField(default=False)),
                ('total_tables', models.IntegerField(default=0)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('logo', models.JSONField(default=list)),
                ('fssai', models.JSONField(default=list)),
                ('hsn', models.JSONField(default=list)),
                ('modified_at', models.JSONField(blank=True, default=list)),
                ('modified_by', models.JSONField(blank=True, default=list)),
                ('restaurant_cgst', models.DecimalField(decimal_places=2, default=2.5, help_text='Restaurant CGST rate in percentage', max_digits=4)),
                ('restaurant_sgst', models.DecimalField(decimal_places=2, default=2.5, help_text='Restaurant SGST rate in percentage', max_digits=4)),
                ('hotel_cgst_lower', models.DecimalField(decimal_places=2, default=6.0, help_text='Hotel CGST rate for rooms below limit margin', max_digits=4)),
                ('hotel_sgst_lower', models.DecimalField(decimal_places=2, default=6.0, help_text='Hotel SGST rate for rooms below limit margin', max_digits=4)),
                ('hotel_cgst_upper', models.DecimalField(decimal_places=2, default=9.0, help_text='Hotel CGST rate for rooms above limit margin', max_digits=4)),
                ('hotel_sgst_upper', models.DecimalField(decimal_places=2, default=9.0, help_text='Hotel SGST rate for rooms above limit margin', max_digits=4)),
                ('service_cgst_lower', models.DecimalField(decimal_places=2, default=9.0, help_text='Service CGST rate for services below limit margin', max_digits=4)),
                ('service_sgst_lower', models.DecimalField(decimal_places=2, default=9.0, help_text='Service SGST rate for services below limit margin', max_digits=4)),
                ('service_cgst_upper', models.DecimalField(decimal_places=2, default=14.0, help_text='Service CGST rate for services above limit margin', max_digits=4)),
                ('service_sgst_upper', models.DecimalField(decimal_places=2, default=14.0, help_text='Service SGST rate for services above limit margin', max_digits=4)),
                ('hotel_gst_limit_margin', models.DecimalField(decimal_places=2, default=7500.0, help_text='Price threshold for different room GST rates', max_digits=10)),
                ('service_gst_limit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Price threshold for different service GST rates (if null, lower rate applies)', max_digits=10, null=True)),
                ('subscription_from', models.DateField(blank=True, null=True)),
                ('subscription_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('verification_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'verification_id'], name='accounts_ph_phone_b4310a_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer'), ('guest', 'Guest')], default='customer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
