# Generated by Django 5.2 on 2025-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_cgst_lower',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_cgst_upper',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_gst_limit_margin',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_sgst_lower',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_sgst_upper',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='restaurant_cgst',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='restaurant_sgst',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='service_cgst_lower',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='service_cgst_upper',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='service_gst_limit_margin',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='service_sgst_lower',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='service_sgst_upper',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_from',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_to',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='total_tables',
        ),
        migrations.AddField(
            model_name='tenant',
            name='food_cgst',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='food_sgst',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_cgst',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_cgst_premium',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_gst_threshold',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_sgst',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_sgst_premium',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_cgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_sgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
    ]
