# Generated by Django 5.2 on 2025-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_tenant_name_tenant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='room_gst_threshold',
            new_name='gst_threshold',
        ),
        migrations.AddField(
            model_name='tenant',
            name='food_cgst_premium',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='food_sgst_premium',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
    ]
