# Generated by Django 5.2 on 2025-04-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_room_gst_threshold_tenant_gst_threshold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='tenant_name',
        ),
    ]
