# Generated by Django 5.0.7 on 2024-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='tenant_name',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
