# Generated by Django 5.0.7 on 2024-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_name_tenant_tenant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tenant_admin',
        ),
    ]
