# Generated by Django 5.0.7 on 2024-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_tenant_address_line_1_tenant_address_line_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='phone_number',
            new_name='alt_phone',
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
