# Generated by Django 5.0.7 on 2024-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
