# Generated by Django 5.0.7 on 2024-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_tenant_alt_phone_alter_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='total_tables',
            field=models.IntegerField(default=0),
        ),
    ]
