# Generated by Django 5.0.7 on 2024-07-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_tenant_total_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='total_tables',
        ),
    ]
