# Generated by Django 5.1 on 2024-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
