# Generated by Django 5.1.1 on 2024-09-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
    ]
