# Generated by Django 5.1.1 on 2024-09-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_table_tenant'),
        ('order', '0008_alter_order_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
