# Generated by Django 5.1.1 on 2024-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
