# Generated by Django 5.1.1 on 2024-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_tenant_logo_url_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.JSONField(default=list),
        ),
    ]
