# Generated by Django 5.1.1 on 2024-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_tenant_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
