# Generated by Django 5.1.1 on 2024-09-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_tenant_logo_tenant_image_tenant_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='image',
            new_name='logo',
        ),
    ]
