# Generated by Django 5.1.1 on 2024-09-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_image_tenant_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='logo',
            new_name='image',
        ),
    ]
