# Generated by Django 5.1.1 on 2024-09-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_logo_tenant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='image',
            new_name='logo',
        ),
    ]
