# Generated by Django 5.1.1 on 2024-09-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_image_tenant_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='gst_in',
            new_name='gst',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_at',
        ),
    ]
