# Generated by Django 5.1.1 on 2024-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_gst_in_tenant_gst_remove_tenant_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modified_at',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modified_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
