# Generated by Django 5.1.1 on 2024-09-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_tenant_modified_at_tenant_modified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='gst',
            new_name='gst_no',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='domain_url',
        ),
        migrations.AddField(
            model_name='tenant',
            name='food_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_gst_limit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_gst_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_gst_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
