# Generated by Django 5.1.1 on 2024-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_rename_gst_tenant_gst_no_remove_tenant_domain_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='food_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
