# Generated by Django 5.1.1 on 2024-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_tenant_food_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='hotel_gst_limit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
