# Generated by Django 5.1.1 on 2024-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_tenant_hotel_gst_limit_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
