# Generated by Django 5.1.1 on 2024-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_tenant_subscription_from_tenant_subscription_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
