# Generated by Django 5.1.1 on 2024-10-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_address_line_1_user_address_line_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
