# Generated by Django 5.1.2 on 2024-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='food_gst',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_gst_lower',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hotel_gst_upper',
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_cgst_lower',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Hotel CGST rate for rooms below limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_cgst_upper',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Hotel CGST rate for rooms above limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_sgst_lower',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Hotel SGST rate for rooms below limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hotel_sgst_upper',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Hotel SGST rate for rooms above limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='restaurant_cgst',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Restaurant CGST rate in percentage', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='restaurant_sgst',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Restaurant SGST rate in percentage', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_cgst_lower',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Service CGST rate for services below limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_cgst_upper',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Service CGST rate for services above limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_gst_limit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price threshold for different service GST rates (if null, lower rate applies)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_sgst_lower',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Service SGST rate for services below limit margin', max_digits=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_sgst_upper',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Service SGST rate for services above limit margin', max_digits=4),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='hotel_gst_limit_margin',
            field=models.DecimalField(decimal_places=2, default=7500.0, help_text='Price threshold for different room GST rates', max_digits=10),
        ),
    ]
