# Generated by Django 5.1.6 on 2025-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fssai',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hsn',
            field=models.JSONField(default=list),
        ),
    ]
