# Generated by Django 5.1 on 2024-08-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_role'),
        ('hotel', '0003_remove_room_past_bookings_pastbooking_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='past_bookings',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
        migrations.DeleteModel(
            name='PastBooking',
        ),
    ]
