# Generated by Django 5.1 on 2024-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_room_past_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
