# Generated by Django 5.1 on 2024-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
