# Generated by Django 5.1 on 2024-08-31 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_user_dob'),
        ('hotel', '0011_alter_booking_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
            preserve_default=False,
        ),
    ]
