# Generated by Django 5.1 on 2024-08-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_booking_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
