# Generated by Django 5.1 on 2024-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scenario',
            field=models.IntegerField(choices=[(1, 'Single ID for entire booking'), (2, 'Single ID per room'), (3, 'All guests ID')], default=1),
        ),
    ]
