# Generated by Django 5.1 on 2024-08-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_remove_booking_room_booking_rooms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
