# Generated by Django 5.1 on 2024-08-31 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_servicecategory_booking_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_breakdown',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Credit Card'), (3, 'Debit Card'), (4, 'UPI'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scenario',
            field=models.IntegerField(choices=[(1, 'Single ID for entire booking'), (2, 'Single ID per room'), (3, 'All guests ID')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
