# Generated by Django 5.1 on 2024-08-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_rename_room_booking_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
