# Generated by Django 5.1 on 2024-09-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_alter_booking_booking_date_alter_booking_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
