# Generated by Django 5.1 on 2024-09-02 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_dob'),
        ('hotel', '0022_remove_service_category_delete_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Checked-in'), (5, 'Checked-out'), (6, 'No-show')], default=1)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'Cash'), (2, 'Credit Card'), (3, 'Debit Card'), (4, 'UPI'), (5, 'Other')], default=1)),
                ('scenario', models.IntegerField(choices=[(1, 'Single ID for entire booking'), (2, 'Single ID per room'), (3, 'All guests ID')], default=1)),
                ('identification', models.JSONField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, to='hotel.room')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
    ]
