# Generated by Django 5.1 on 2024-09-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_rooms', to='hotel.booking'),
        ),
    ]
