# Generated by Django 5.1 on 2024-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_rename_total_amount_booking_total_amount_per_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_periods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=20),
        ),
    ]
