# Generated by Django 5.1 on 2024-09-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_room_booked_periods_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='identification',
        ),
    ]
