# Generated by Django 5.1 on 2024-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_remove_booking_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
