# Generated by Django 5.1 on 2024-09-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_remove_room_booking_id_room_beds_room_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_date',
        ),
    ]
