# Generated by Django 5.1 on 2024-09-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_remove_booking_from_date_remove_booking_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
