# Generated by Django 5.1 on 2024-09-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_from_date_booking_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_date',
        ),
    ]
