# Generated by Django 5.1.1 on 2024-09-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_servicecategory_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
