# Generated by Django 5.1.1 on 2024-09-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked_periods',
        ),
    ]
