# Generated by Django 5.1.1 on 2024-09-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_remove_room_booked_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='images',
            new_name='image',
        ),
    ]
