# Generated by Django 5.1.1 on 2024-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_billing_booking_payment_roombooking_checkout_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
