# Generated by Django 5.1.1 on 2024-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_roombooking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_card',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
