# Generated by Django 5.1.1 on 2024-09-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_booking_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_card',
        ),
    ]
