# Generated by Django 5.1.1 on 2024-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_remove_booking_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_card',
            field=models.JSONField(default=list),
        ),
    ]
