# Generated by Django 5.1.1 on 2024-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0042_booking_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_card',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
