# Generated by Django 5.1.1 on 2024-09-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_alter_booking_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
    ]
