# Generated by Django 5.1.1 on 2024-09-29 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_remove_checkin_status_remove_checkout_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='guests',
            field=models.ManyToManyField(related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
    ]
