# Generated by Django 5.1.1 on 2024-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_guestdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='guest_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
