# Generated by Django 5.1.1 on 2024-09-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_guestdetails_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='c_form',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
