# Generated by Django 5.1.1 on 2024-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_guestdetails_c_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='foreigner',
            field=models.BooleanField(default=False),
        ),
    ]
