# Generated by Django 5.1.1 on 2024-10-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_room_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceusage',
            old_name='room_booking',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='serviceusage',
            old_name='service',
            new_name='service_id',
        ),
        migrations.AddField(
            model_name='serviceusage',
            name='booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
        ),
    ]
