# Generated by Django 5.1.1 on 2024-10-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_tenant_subscription_from_tenant_subscription_to'),
        ('hotel', '0052_service_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
    ]
