# Generated by Django 5.1.1 on 2024-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_tenant_subscription_from_tenant_subscription_to'),
        ('hotel', '0053_servicecategory_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'tenant')},
        ),
    ]
