# Generated by Django 5.1.1 on 2024-10-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_alter_room_room_number_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='status',
        ),
    ]
