# Generated by Django 5.1.1 on 2024-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0055_remove_roombooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked-in'), ('checked_out', 'Checked-out'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
