# Generated by Django 5.1.2 on 2024-10-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('partial_checked_in', 'Partial Checked-in'), ('checked_in', 'Checked-in'), ('checked_out', 'Checked-out'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
