# Generated by Django 5.1.2 on 2024-10-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
        ),
    ]
