# Generated by Django 5.1.2 on 2024-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_billing_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('partial_checked_in', 'Partial Checked-in'), ('checked_in', 'Checked-in'), ('partial_checked_in_out', 'Partial Checked-in and Checked-out'), ('partial_checked_out', 'Partial Checked-out'), ('checked_out', 'Checked-out'), ('no_show', 'No-show')], default='pending', max_length=30),
        ),
    ]
