# Generated by Django 5.1.2 on 2024-10-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='sub_category',
        ),
    ]
