# Generated by Django 5.1.2 on 2024-10-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0060_remove_servicecategory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
