# Generated by Django 5.1.2 on 2024-11-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0061_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
