# Generated by Django 5.1.2 on 2024-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0062_remove_payment_billing_delete_billing_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
