# Generated by Django 5.1.2 on 2024-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_alter_checkin_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
    ]
