# Generated by Django 5.1.2 on 2024-11-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0064_alter_checkin_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
