# Generated by Django 5.1.2 on 2024-11-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0065_alter_checkout_check_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceusage',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='serviceusage',
            name='total_price',
        ),
    ]
