# Generated by Django 5.1.3 on 2024-11-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0066_remove_serviceusage_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
