# Generated by Django 5.2 on 2025-04-14 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('foods', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.JSONField(blank=True, default=list)),
                ('modified_by', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('kot', 'Kot'), ('served', 'Served'), ('settled', 'Setted'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('order_type', models.CharField(choices=[('take_away', 'Take Away'), ('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('online', 'Online'), ('hotel', 'Hotel')], default='dine_in', max_length=20)),
                ('quantity', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('kot_count', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('food_items', models.ManyToManyField(to='foods.fooditem')),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room')),
                ('tables', models.ManyToManyField(blank=True, related_name='orders', to='foods.table')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.tenant')),
            ],
        ),
    ]
