# Generated by Django 5.0.7 on 2024-08-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_type_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
