# Generated by Django 5.1.1 on 2024-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('kot', 'Kot'), ('served', 'Served'), ('billed', 'Billed'), ('settled', 'Setted'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
