# Generated by Django 5.1.1 on 2024-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_kot_count_order_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
