# Generated by Django 5.1.1 on 2024-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_updated_by_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
