# Generated by Django 5.1.1 on 2024-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_updated_by_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
