# Generated by Django 5.1.1 on 2024-09-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_updated_at_alter_order_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
    ]
