# Generated by Django 5.1.1 on 2024-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_updated_at_remove_order_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kot_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
