# Generated by Django 5.1.1 on 2024-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_kot_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kot_count',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
