# Generated by Django 5.1.1 on 2024-09-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_kot_count_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
