# Generated by Django 5.1.1 on 2024-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kot_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
