# Generated by Django 5.1.1 on 2024-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_kot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
