# Generated by Django 5.1.1 on 2024-09-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_modified_at_order_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
