# Generated by Django 5.1.1 on 2024-09-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_rename_images_room_image'),
        ('order', '0021_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hotel.room'),
        ),
    ]
