# Generated by Django 5.1.1 on 2024-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kot_count',
            field=models.IntegerField(default=0),
        ),
    ]
