# Generated by Django 5.1.1 on 2024-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0031_alter_table_table_number_alter_table_unique_together'),
        ('order', '0023_alter_order_kot_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='orders', to='foods.table'),
        ),
    ]
