# Generated by Django 5.1.1 on 2024-10-06 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_rename_room_booking_serviceusage_room_id_and_more'),
        ('order', '0024_remove_order_table_order_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.AddField(
            model_name='order',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking'),
        ),
        migrations.AddField(
            model_name='order',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
    ]
