# Generated by Django 5.1.1 on 2024-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0032_table_order'),
        ('order', '0025_remove_order_room_order_booking_id_order_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='foods.table'),
        ),
    ]
