# Generated by Django 5.1.2 on 2024-10-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_net_amount_order_sub_total_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
