# Generated by Django 5.1.2 on 2024-11-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_discount_order_sub_total_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='net_total',
        ),
    ]
