# Generated by Django 5.1.2 on 2024-11-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_rename_total_amount_order_net_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sub_total',
            new_name='total',
        ),
    ]
