# Generated by Django 5.1.2 on 2024-11-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_rename_sub_total_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='net_total',
        ),
    ]
