# Generated by Django 5.1.2 on 2024-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_remove_order_discount_remove_order_net_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='net_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
