# Generated by Django 5.1.2 on 2024-11-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_discount_order_net_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
