# Generated by Django 5.1.2 on 2024-11-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_remove_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='net_total',
        ),
    ]
