# Generated by Django 5.1.2 on 2024-11-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0032_table_order'),
        ('order', '0035_remove_order_net_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='orders', to='foods.table'),
        ),
    ]
