# Generated by Django 5.1.2 on 2024-11-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_order_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('kot', 'Kot'), ('served', 'Served'), ('settled', 'Setted'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
